/**
 * Generate Base64-Embedded Font Data for Night Sheet PDF Export
 *
 * Run: node scripts/generateFontEmbeds.js
 *
 * This creates src/ts/nightOrder/embeddedFonts.ts with pre-encoded fonts
 * so Snapdom doesn't need to fetch and convert them at runtime.
 */

const fs = require('fs');
const path = require('path');

const FONTS = [
  {
    family: 'Dumbledor',
    file: 'assets/fonts/Dumbledor/Dumbledor.ttf',
    format: 'truetype',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Goudy Old Style',
    file: 'assets/fonts/GoudyOldStyle/GoudyOldStyle.ttf',
    format: 'truetype',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'TradeGothic',
    file: 'assets/fonts/TradeGothic/TradeGothic.otf',
    format: 'opentype',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'TradeGothicBold',
    file: 'assets/fonts/TradeGothic/TradeGothicBold.otf',
    format: 'opentype',
    weight: 'bold',
    style: 'normal',
  },
];

function generateEmbeddedFonts() {
  const fontData = FONTS.map((font) => {
    const filePath = path.join(process.cwd(), font.file);
    const buffer = fs.readFileSync(filePath);
    const base64 = buffer.toString('base64');
    const mimeType = font.format === 'truetype' ? 'font/ttf' : 'font/otf';

    console.log(
      `Encoded ${font.family}: ${(buffer.length / 1024).toFixed(1)}KB -> ${(base64.length / 1024).toFixed(1)}KB base64`
    );

    return {
      ...font,
      dataUrl: `data:${mimeType};base64,${base64}`,
    };
  });

  const fontArrayStr = JSON.stringify(fontData, null, 2);

  const output = `/**
 * Pre-Encoded Night Sheet Fonts
 *
 * Generated by: node scripts/generateFontEmbeds.js
 *
 * These fonts are pre-encoded as base64 data URLs so Snapdom
 * doesn't need to fetch and convert them at runtime (~13s savings).
 */

export interface EmbeddedFont {
  family: string;
  dataUrl: string;
  format: 'truetype' | 'opentype';
  weight: string;
  style: string;
}

export const NIGHT_SHEET_FONTS: EmbeddedFont[] = ${fontArrayStr};

/**
 * Generate CSS @font-face rules for embedded fonts
 */
export function generateFontFaceCSS(): string {
  return NIGHT_SHEET_FONTS.map(
    (font) =>
      \`@font-face {
  font-family: "\${font.family}";
  src: url("\${font.dataUrl}") format("\${font.format}");
  font-weight: \${font.weight};
  font-style: \${font.style};
}\`
  ).join('\\n\\n');
}
`;

  const outputPath = path.join(process.cwd(), 'src/ts/nightOrder/embeddedFonts.ts');
  fs.writeFileSync(outputPath, output);

  console.log(`\nGenerated: ${outputPath}`);
  console.log(`Total size: ${(output.length / 1024).toFixed(1)}KB`);
}

generateEmbeddedFonts();
