/**
 * Random Name Generator for Blood on the Clocktower Characters
 *
 * Generates thematic names from a curated list of mythological and mystical words.
 */

// ============================================
// WORD LIST - Mythological and Mystical Words
// ============================================

const ALL_NAMES: string[] = [
  'Abbess',
  'Academic',
  'Acharya',
  'Achelous',
  'Acheron',
  'Achilles',
  'Acolyte',
  'Acrisius',
  'Actaeon',
  'Actian',
  'Actor',
  'Acylas',
  'Adamant',
  'Adamantine',
  'Adamite',
  'Addax',
  'Adept',
  'Aedile',
  'Aeolos',
  'Aesir',
  'Aether',
  'Afreet',
  'Afrit',
  'Aga',
  'Agha',
  'Ajax',
  'Alderman',
  'Alfar',
  'Almoner',
  'Alto',
  'Amazons',
  'Amir',
  'Amira',
  'Ammit',
  'Amphisbaena',
  'Anchises',
  'Anchorite',
  'Andromeda',
  'Antaeus',
  'Antioch',
  'Anubis',
  'Anuket',
  'Anunnaki',
  'Apatia',
  'Apep',
  'Aphrodite',
  'Apollo',
  'Apothecary',
  'Apsara',
  'Aquilo',
  'Arachne',
  'Arbalist',
  'Archbishop',
  'Archer',
  'Archivist',
  'Archon',
  'Ares',
  'Arethusa',
  'Argonaut',
  'Argus',
  'Aristaios',
  'Arkas',
  'Armorer',
  'Arquebusier',
  'Artemis',
  'Artemisia',
  'Ascetic',
  'Asclepius',
  'Ashigaru',
  'Astarte',
  'Astraea',
  'Astrologer',
  'Asura',
  'Atalanta',
  'Ate',
  'Athena',
  'Athene',
  'Atlas',
  'Atreus',
  'Atropos',
  'Attis',
  'Augur',
  'Augustus',
  'Bacchant',
  'Bagpiper',
  'Bailiff',
  'Bakeneko',
  'Baldr',
  'Ban',
  'Bandit',
  'Bandmaster',
  'Banus',
  'Bard',
  'Barghest',
  'Baritone',
  'Basilisk',
  'Bass',
  'Bassist',
  'Bastet',
  'Baxia',
  'Bedouin',
  'Behemoth',
  'Bellfounder',
  'Bennu',
  'Beowulf',
  'Berber',
  'Berserker',
  'Bey',
  'Bhikkhu',
  'Bifrost',
  'Bikku',
  'Binder',
  'Bishamonten',
  'Blacksmith',
  'Blademaster',
  'Bloodletter',
  'Bonesetter',
  'Bookbinder',
  'Bowman',
  'Bowmaster',
  'Bowyer',
  'Boyar',
  'Bragi',
  'Brahmin',
  'Brehon',
  'Bricklayer',
  'Brickmaker',
  'Brigand',
  'Brisingamen',
  'Brunhild',
  'Buccaneer',
  'Bunyip',
  'Burgrave',
  'Busyrane',
  'Byleistr',
  'Cabalist',
  'Cabiri',
  'Cacodemon',
  'Cadi',
  'Caesar',
  'Cailleach',
  'Calif',
  'Caliph',
  'Calligrapher',
  'Calypso',
  'Camazotz',
  'Camenae',
  'Canon',
  'Cantor',
  'Carder',
  'Carpenter',
  'Cartographer',
  'Cartwright',
  'Carver',
  'Castellan',
  'Cataphract',
  'Cathar',
  'Celestial',
  'Cellist',
  'Censor',
  'Centaur',
  'Centimani',
  'Centurion',
  'Ceramicist',
  'Cerberus',
  'Chakravartin',
  'Chalchiuhtlicue',
  'Chandler',
  'Changeling',
  'Chantress',
  'Chaplain',
  'Charcoal',
  'Charybdis',
  'Chatelaine',
  'Chieftain',
  'Chimera',
  'Chirurgeon',
  'Churl',
  'Clarinettist',
  'Clotho',
  'Clurichaun',
  'Cockatrice',
  'Collector',
  'Collegian',
  'Collier',
  'Comber',
  'Composer',
  'Condottiero',
  'Conductor',
  'Confessor',
  'Conjurer',
  'Conjuror',
  'Conqueror',
  'Conquistador',
  'Conscript',
  'Constable',
  'Consul',
  'Cooper',
  'Cordwainer',
  'Corsair',
  'Cossack',
  'Count',
  'Courier',
  'Crossbowman',
  'Cuirassier',
  'Cyclops',
  'Dagan',
  'Daimon',
  'Daimyo',
  'Danaans',
  'Danaus',
  'Daoist',
  'Dazdbog',
  'Decurion',
  'Demeter',
  'Demonologist',
  'Dentist',
  'Dervish',
  'Despina',
  'Despoina',
  'Despot',
  'Deukalion',
  'Deva',
  'Devata',
  'Dey',
  'Dictator',
  'Dionysus',
  'Disir',
  'Diviner',
  'Dokkaebi',
  'Dominus',
  'Domovoi',
  'Dragon',
  'Dragoon',
  'Drake',
  'Draper',
  'Draugr',
  'Druid',
  'Drummer',
  'Dryad',
  'Duergar',
  'Duke',
  'Dwarf',
  'Dyer',
  'Earl',
  'Echidna',
  'Einherjar',
  'Elf',
  'Embalmer',
  'Embroiderer',
  'Emir',
  'Emira',
  'Empusa',
  'Enchantress',
  'Engraver',
  'Entertainer',
  'Ephor',
  'Ereshkigal',
  'Erinyes',
  'Esquire',
  'Eunuch',
  'Executioner',
  'Fae',
  'Faerie',
  'Fakir',
  'Falconer',
  'Faoladh',
  'Faqir',
  'Fenghuang',
  'Fenrir',
  'Fetishist',
  'Fili',
  'Filid',
  'Firebird',
  'Flagellant',
  'Flautist',
  'Fletcher',
  'Flutist',
  'Franklin',
  'Freeman',
  'Fuller',
  'Fury',
  'Gaki',
  'Gamekeeper',
  'Gandharva',
  'Gaoler',
  'Garuda',
  'Gatekeeper',
  'Gentleman',
  'Gentlewoman',
  'Ghul',
  'Gladiator',
  'Glassblower',
  'Glassmaker',
  'Glazier',
  'Gnostic',
  'Godi',
  'Goldsmith',
  'Gorgon',
  'Governor',
  'Grace',
  'Gravedigger',
  'Grenadier',
  'Grendel',
  'Griffin',
  'Gugalanna',
  'Gumiho',
  'Guru',
  'Gwisin',
  'Haberdasher',
  'Hades',
  'Hafiz',
  'Halberdier',
  'Hanuman',
  'Harbormaster',
  'Harper',
  'Harpist',
  'Haruspex',
  'Hasid',
  'Hasidim',
  'Headsman',
  'Healer',
  'Healress',
  'Hecate',
  'Helios',
  'Hephaestus',
  'Hera',
  'Heracles',
  'Herald',
  'Herbalist',
  'Herbwife',
  'Hercules',
  'Hermes',
  'Hermione',
  'Heros',
  'Hestia',
  'Highwayman',
  'Hippocamp',
  'Hoplite',
  'Horus',
  'Houngan',
  'Hounsi',
  'Huitzilopochtli',
  'Huscarl',
  'Hussar',
  'Hussite',
  'Huxian',
  'Hydra',
  'Hyperion',
  'Iapetus',
  'Iblis',
  'Ichor',
  'Ifrit',
  'Imam',
  'Immortal',
  'Imperator',
  'Incubus',
  'Indigene',
  'Indra',
  'Initiate',
  'Inquisitor',
  'Intercessor',
  'Interpreter',
  'Inugami',
  'Isis',
  'Jackal',
  'Jacobite',
  'Jambavan',
  'Janissary',
  'Jarl',
  'Jataka',
  'Jeevaka',
  'Jester',
  'Jeweler',
  'Jiangshi',
  'Jinn',
  'Jinni',
  'Jocasta',
  'Joiner',
  'Jormungandr',
  'Jotun',
  'Kabbalist',
  'Kaid',
  'Kali',
  'Kama',
  'Kamadeva',
  'Kamadhenu',
  'Kami',
  'Kappa',
  'Keeper',
  'Kelpie',
  'Keyholder',
  'Keymaster',
  'Khalif',
  'Khalifah',
  'Khan',
  'Khanum',
  'Khatib',
  'Kikimora',
  'Kinnara',
  'Kinnari',
  'Kitsune',
  'Knez',
  'Knyaz',
  'Kodama',
  'Koios',
  'Kreios',
  'Kronos',
  'Kshatriya',
  'Kumiho',
  'Kunoichi',
  'Kylin',
  'Lacemaker',
  'Lachesis',
  'Lady',
  'Laima',
  'Lamia',
  'Lancer',
  'Landgrave',
  'Lares',
  'Leech',
  'Legionary',
  'Lemur',
  'Leprechaun',
  'Leshy',
  'Lich',
  'Lindworm',
  'Lollard',
  'Longbowman',
  'Longnü',
  'Lord',
  'Lung',
  'Luthier',
  'Lutist',
  'Lyrist',
  'Maenad',
  'Maestro',
  'Magistrate',
  'Makara',
  'Mambo',
  'Mamluk',
  'Mandarin',
  'Manticore',
  'Marabout',
  'Marauder',
  'Margrave',
  'Marid',
  'Maronite',
  'Marquis',
  'Mercer',
  'Merrow',
  'Midwife',
  'Miller',
  'Milliner',
  'Millwright',
  'Miner',
  'Minotaur',
  'Mitnagid',
  'Mnemosyne',
  'Moirai',
  'Monophysite',
  'Morabito',
  'Morrigan',
  'Muezzin',
  'Mufti',
  'Mullah',
  'Muse',
  'Musician',
  'Musketeer',
  'Mystic',
  'Naga',
  'Naiad',
  'Namtar',
  'Navigator',
  'Necromancer',
  'Nekomata',
  'Nereid',
  'Nestorian',
  'Ninja',
  'Nixie',
  'Norn',
  'Nymph',
  'Oboist',
  'Occultist',
  'Ollam',
  'Onryo',
  'Optio',
  'Orator',
  'Oread',
  'Organbuilder',
  'Organist',
  'Osiris',
  'Ottoman',
  'Ouroboros',
  'Outlaw',
  'Outrider',
  'Palatine',
  'Pan',
  'Pascha',
  'Pasha',
  'Pavior',
  'Peasant',
  'Pegasus',
  'Peltast',
  'Penates',
  'Penitent',
  'Percussionist',
  'Performer',
  'Persephone',
  'Perun',
  'Pharaoh',
  'Phoenix',
  'Phrai',
  'Phret',
  'Pikeman',
  'Pilgrim',
  'Piper',
  'Pirate',
  'Pisacha',
  'Plasterer',
  'Pochteca',
  'Poet',
  'Polemarch',
  'Porter',
  'Poseidon',
  'Potamid',
  'Potter',
  'Praetor',
  'Pret',
  'Pretha',
  'Priestess',
  'Priesthood',
  'Prince',
  'Princeps',
  'Privateer',
  'Puca',
  'Pundit',
  'Qadi',
  'Qaid',
  'Qareen',
  'Qazi',
  'Qilin',
  'Quaestor',
  'Quarryman',
  'Quartermaster',
  'Quetzalcoatl',
  'Raider',
  'Rais',
  'Rakshasa',
  'Reeve',
  'Regent',
  'Revenant',
  'Rhetorician',
  'Ronin',
  'Runes',
  'Runescribe',
  'Rusalka',
  'Ryu',
  'Sacerdote',
  'Sadhu',
  'Safavid',
  'Sailmaker',
  'Samurai',
  'Sansin',
  'Sanyassi',
  'Satyr',
  'Sawyer',
  'Saxophonist',
  'Scarab',
  'Scribe',
  'Sculptor',
  'Scylla',
  'Seannachie',
  'Seeker',
  'Seeress',
  'Sekhmet',
  'Seljuk',
  'Selkie',
  'Seneschal',
  'Serf',
  'Shade',
  'Shaitan',
  'Shaman',
  'Shamana',
  'Shearman',
  'Sheikh',
  'Shinigami',
  'Shinobi',
  'Shogun',
  'Shudra',
  'Sibyl',
  'Sidhe',
  'Signifer',
  'Silenus',
  'Silversmith',
  'Simurgh',
  'Singer',
  'Sipahi',
  'Siren',
  'Skald',
  'Skoptsy',
  'Soothsayer',
  'Soprano',
  'Sorcerer',
  'Sorceress',
  'Spearman',
  'Specter',
  'Sphinx',
  'Spinner',
  'Squire',
  'Starosta',
  'Stonecutter',
  'Stribog',
  'Stylite',
  'Sufi',
  'Sultan',
  'Sultana',
  'Surgeon',
  'Svarog',
  'Swami',
  'Sylph',
  'Taborite',
  'Tailor',
  'Tanner',
  'Tanuki',
  'Taoist',
  'Taotie',
  'Tengu',
  'Tenor',
  'Tezcatlipoca',
  'Thane',
  'Thatcher',
  'Thegn',
  'Themis',
  'Theurge',
  'Thoth',
  'Thrall',
  'Tiamat',
  'Tiler',
  'Titan',
  'Tlaloc',
  'Tlatoani',
  'Totemist',
  'Tribune',
  'Troll',
  'Troubadour',
  'Trumpeter',
  'Tsar',
  'Tsarina',
  'Tuareg',
  'Typhon',
  'Tzaddiq',
  'Tzar',
  'Uhlan',
  'Vaishya',
  'Valkyr',
  'Valkyrie',
  'Vampire',
  'Vanara',
  'Vanir',
  'Vassal',
  'Veles',
  'Vestal',
  'Vetala',
  'Villein',
  'Violinist',
  'Vocalist',
  'Voivoda',
  'Voivode',
  'Volos',
  'Völva',
  'Wadjet',
  'Wainwright',
  'Waldensian',
  'Wali',
  'Warden',
  'Warlord',
  'Weaver',
  'Werewolf',
  'Wheelwright',
  'Wyrm',
  'Wyvern',
  'Xian',
  'Xiezhi',
  'Yaksha',
  'Yaoguai',
  'Yeoman',
  'Ymir',
  'Yogi',
  'Yogin',
  'Yokai',
  'Youkai',
  'Yurei',
  'Zeus',
  'Zhenniao',
  'Zipacna',
  'Zmey',
];

// ============================================
// GENERATOR FUNCTIONS
// ============================================

/**
 * Generate a random name from the word list
 * @returns A random name string
 */
export function generateRandomName(): string {
  const randomIndex = Math.floor(Math.random() * ALL_NAMES.length);
  return ALL_NAMES[randomIndex];
}

/**
 * Generate multiple unique random names
 * @param count - Number of names to generate
 * @returns Array of unique random names
 */
export function generateMultipleNames(count: number): string[] {
  const shuffled = [...ALL_NAMES].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}

/**
 * Convert a name to a valid ID (snake_case, lowercase)
 * @param name - The name to convert
 * @returns A snake_case ID string
 */
export function nameToId(name: string): string {
  return name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s]/g, '') // Remove special characters
    .replace(/\s+/g, '_'); // Replace spaces with underscores
}

/**
 * Generate a new UUID for character identification
 * @returns A UUID string
 */
export function generateUuid(): string {
  return crypto.randomUUID();
}

/**
 * UUID v5 namespace for character identification
 * Uses a custom namespace specific to this application
 */
const CHARACTER_UUID_NAMESPACE = 'a8f3e1c9-4b2d-5e6f-8a9b-3c4d5e6f7a8b';

/**
 * Convert Uint8Array to UUID format string
 * @param bytes - Byte array (must be 16 bytes)
 * @returns UUID string with dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
 */
function bytesToUuid(bytes: Uint8Array): string {
  const hex = Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');

  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

/**
 * Generate a stable UUID v5 using SHA-1 (RFC 4122 compliant)
 *
 * This implementation uses SHA-1 cryptographic hashing to create collision-resistant UUIDs.
 * Replaces the previous FNV-1a implementation which had collision vulnerabilities.
 *
 * @param characterId - Character ID (e.g., "seamstress", "scapegoat")
 * @param characterName - Character name (e.g., "Seamstress", "Scapegoat")
 * @returns Promise resolving to UUID string
 *
 * @example
 * ```typescript
 * // Different characters will ALWAYS get different UUIDs
 * const seamstressUuid = await generateStableUuid('seamstress', 'Seamstress');
 * const scapegoatUuid = await generateStableUuid('scapegoat', 'Scapegoat');
 * // seamstressUuid !== scapegoatUuid (guaranteed - no more collisions!)
 *
 * // Same inputs always produce same UUID (deterministic)
 * const uuid1 = await generateStableUuid('washerwoman', 'Washerwoman');
 * const uuid2 = await generateStableUuid('washerwoman', 'Washerwoman');
 * // uuid1 === uuid2 (true)
 * ```
 */
export async function generateStableUuid(
  characterId: string,
  characterName: string
): Promise<string> {
  // Normalize inputs to ensure consistency
  const normalizedId = characterId.toLowerCase().trim();
  const normalizedName = characterName.trim();

  // Create namespace-qualified input
  const input = `${CHARACTER_UUID_NAMESPACE}:${normalizedId}:${normalizedName}`;

  // SHA-1 hash using Web Crypto API (RFC 4122 standard for UUID v5)
  const encoder = new TextEncoder();
  const data = encoder.encode(input);
  const hashBuffer = await crypto.subtle.digest('SHA-1', data);

  // Convert hash to byte array (SHA-1 produces 20 bytes, we need 16 for UUID)
  const hashBytes = new Uint8Array(hashBuffer);

  // Take first 16 bytes for UUID
  const uuidBytes = new Uint8Array(16);
  for (let i = 0; i < 16; i++) {
    uuidBytes[i] = hashBytes[i];
  }

  // Set version (5) and variant bits per RFC 4122
  uuidBytes[6] = (uuidBytes[6] & 0x0f) | 0x50; // Version 5: 0101xxxx
  uuidBytes[8] = (uuidBytes[8] & 0x3f) | 0x80; // Variant: 10xxxxxx

  // Convert to UUID string format
  return bytesToUuid(uuidBytes);
}
